const storyText = [
            "Die Morgensonne wirft ihre ersten Strahlen auf die glänzende Oberfläche des Raumschiffs Aurora.",
            "Captain Sarah Chen steht auf der Kommandobrücke und beobachtet die schimmernden Ringe des Saturn.",
            "Die Sensoren des Schiffs erfassen plötzlich ein ungewöhnliches Signal aus dem Asteroidengürtel.",
            "Erste Analysen zeigen Energiemuster die keiner bekannten Quelle entsprechen.",
            "Die Wissenschaftsoffiziere Dr. Rodriguez und Dr. Patel untersuchen die rätselhaften Daten.",
            "Ein kleiner Asteroid beginnt in unnatürlichen Mustern zu pulsieren.",
            "Die Oberfläche des Himmelskörpers scheint sich wie flüssiges Metall zu verformen.",
            "Aus dem Inneren des Asteroiden dringt ein bläuliches Leuchten.",
            "Die Crew der Aurora beobachtet gebannt die Transformation.",
            "Das Kommunikationssystem empfängt eine Serie mathematischer Sequenzen.",
            "Dr. Patel entdeckt in den Sequenzen ein wiederkehrendes Muster.",
            "Die Zahlenfolgen ähneln einem uralten binären Code.",
            "Captain Chen befiehlt der Crew absolute Funkstille.",
            "Der pulsierende Asteroid bewegt sich langsam auf die Aurora zu.",
            "Die Navigationssysteme melden eine Anomalie im Schwerefeld.",
            "Plötzlich erscheint ein holografisches Symbol im Kommandoraum.",
            "Die fremden Zeichen scheinen eine Art Einladung zu sein.",
            "Dr. Rodriguez erkennt Ähnlichkeiten mit antiken Hieroglyphen.",
            "Das Forschungsteam bereitet eine bemannte Mission zum Asteroiden vor.",
            "Techniker überprüfen die Raumanzüge auf ihre Funktionsfähigkeit.",
            "Die Bordcomputer berechnen einen sicheren Landevektor.",
            "Ein kleines Shuttle löst sich von der Aurora.",
            "Dr. Patel und zwei Ingenieure nähern sich vorsichtig der leuchtenden Oberfläche.",
            "Die Instrumente zeigen ungewöhnliche Quantenfluktuationen.",
            "Eine verborgene Öffnung erscheint in der metallischen Hülle.",
            "Das Innere des Asteroiden enthüllt einen gewaltigen Hohlraum.",
            "Kristalline Strukturen pulsieren im Rhythmus der mathematischen Sequenzen.",
            "Die Crew entdeckt eine Art antike Bibliothek.",
            "Holografische Projektionen erzählen von einer längst vergangenen Zivilisation.",
            "Captain Chen muss eine schwierige Entscheidung treffen.",
            "Die Systeme des Shuttles registrieren eine Energiespitze.",
            "Ein sanftes Vibrieren durchläuft die kristallinen Strukturen.",
            "Die Hologramme beginnen eine Geschichte zu erzählen.",
            "Vor Millionen Jahren existierte eine hochentwickelte Spezies.",
            "Sie hinterließen Wissen in Form von Quantenkristallen.",
            "Dr. Rodriguez analysiert die ersten übersetzten Datenfragmente.",
            "Die fremde Zivilisation warnt vor einer nahenden Gefahr.",
            "Astronomische Berechnungen deuten auf ein katastrophales Ereignis.",
            "Die Aurora empfängt weitere verschlüsselte Nachrichten.",
            "Das Wissenschaftsteam arbeitet fieberhaft an der Entschlüsselung.",
            "Die Kristalle reagieren auf die Anwesenheit der Menschen.",
            "Ein dreidimensionales Modell der Galaxie erscheint.",
            "Rote Markierungen zeigen kritische Bereiche.",
            "Captain Chen lässt einen Notruf zur Erde senden.",
            "Die Kommunikationsoffiziere kämpfen mit Interferenzen.",
            "Dr. Patel macht eine beunruhigende Entdeckung.",
            "Die Zeitachse der Warnung zeigt auf die Gegenwart.",
            "Ein Asteroidenschwarm nähert sich dem Sonnensystem.",
            "Die fremde Technologie bietet möglicherweise einen Ausweg.",
            "Das Team beginnt mit der Aktivierung der Kristallsysteme.",
            "Energie durchströmt die antiken Schaltkreise.",
            "Die Aurora registriert seismische Aktivität im Asteroiden.",
            "Verborgene Maschinen erwachen zum Leben.",
            "Ein Kraftfeld umgibt den gesamten Himmelskörper.",
            "Die Crew kehrt eilig zum Hauptschiff zurück.",
            "Captain Chen ordnet Gefechtsbereitschaft an.",
            "Die Sensoren erfassen multiple Anomalien.",
            "Ein gewaltiger Energieimpuls baut sich auf.",
            "Die Kristalle erreichen kritische Resonanzfrequenzen.",
            "Das Kraftfeld dehnt sich exponentiell aus.",
            "Die Aurora aktiviert ihre Schutzschilde.",
            "Dr. Rodriguez versteht endlich den Plan der Antiken.",
            "Der Asteroid verwandelt sich in eine Verteidigungsstation.",
            "Erste Fragmente des feindlichen Schwarms werden sichtbar.",
            "Die Crew trifft Vorbereitungen für den Kampf.",
            "Techniker installieren die Kristalltechnologie.",
            "Die Bordingenieure modifizieren die Waffensysteme.",
            "Ein Netzwerk von Energiebarrieren entsteht.",
            "Die Erde schickt Verstärkung.",
            "Weitere Raumschiffe erreichen den Saturn.",
            "Eine internationale Flotte formiert sich.",
            "Die Aurora koordiniert die Verteidigungsstellung.",
            "Dr. Patel kalibriert die Kristallmatrix.",
            "Die ersten Asteroiden des feindlichen Schwarms treffen ein.",
            "Das Kraftfeld erfasst die angreifenden Objekte.",
            "Eine gewaltige Energieentladung erschüttert den Raum.",
            "Die modifizierten Waffen zeigen Wirkung.",
            "Captain Chen befiehlt den Gegenangriff.",
            "Die vereinte Flotte rückt vor.",
            "Die Kristalltechnologie übertrifft alle Erwartungen.",
            "Der feindliche Schwarm wird dezimiert.",
            "Die Aurora führt den finalen Angriff.",
            "Ein letzter Energieimpuls beendet die Schlacht.",
            "Die Gefahr für das Sonnensystem ist gebannt.",
            "Die Crew beginnt mit der Analyse der Ereignisse.",
            "Dr. Rodriguez sichert die gewonnenen Daten.",
            "Die Kristalle offenbaren weitere Geheimnisse.",
            "Ein neues Kapitel der Menschheit beginnt.",
            "Die Aurora macht sich bereit für ihre nächste Mission.",
            "Das Vermächtnis der antiken Zivilisation lebt weiter.",
            "Die Sterne warten auf neue Entdeckungen.",
            "Captain Chen gibt den Befehl zum Aufbruch.",
            "Die Triebwerke der Aurora glühen in einem tiefen Blau.",
            "Ein neues Signal erreicht die Kommunikationssysteme.",
            "Die Kristalle haben eine weitere Botschaft entschlüsselt.",
            "In den Tiefen der Galaxie warten weitere Artefakte.",
            "Dr. Rodriguez kartographiert die möglichen Fundorte.",
            "Die internationale Flotte teilt sich die Suchgebiete.",
            "Jedes Schiff erhält spezielle Kristalltechnologie.",
            "Die Wissenschaftler arbeiten an neuen Theorien.",
            "Captain Chen hält eine inspirierende Ansprache.",
            "Die Menschheit steht an der Schwelle zu den Sternen.",
            "Neue Freiwillige melden sich für die Mission.",
            "Die Ausbildung der Crews wird intensiviert.",
            "Spezialisten studieren die antiken Aufzeichnungen.",
            "Ein Netzwerk von Forschungsstationen entsteht.",
            "Die Kristalle enthüllen weitere Geheimnisse.",
            "Dr. Patel entwickelt neue Analysemethoden.",
            "Die Bordcomputer werden permanent aufgerüstet.",
            "Künstliche Intelligenz unterstützt die Forschung.",
            "Die Aurora erreicht unbekannte Sonnensysteme.",
            "Seltsame Signale führen zu neuen Entdeckungen.",
            "Das Team findet weitere kristalline Strukturen.",
            "Jeder Fund enthüllt neue Puzzleteile.",
            "Die Geschichte der Antiken wird klarer.",
            "Eine galaktische Karte nimmt Gestalt an.",
            "Die Crew stößt auf weitere Verteidigungsstationen.",
            "Ein Netzwerk zum Schutz der Galaxie entsteht.",
            "Die Aurora koordiniert die Aktivierung.",
            "Neue Technologien werden erschlossen.",
            "Die Wissenschaftler machen Durchbrüche.",
            "Die Menschheit lernt von den Antiken.",
            "Erste Kolonien werden gegründet.",
            "Die Kristalle dienen als Energiequelle.",
            "Neue Transportwege entstehen zwischen den Sternen.",
            "Die Aurora führt die Expansion an.",
            "Captain Chen wird zur Legende.",
            "Die Crew schreibt Geschichte.",
            "Ein galaktisches Zeitalter beginnt.",
            "Die Sterne sind nicht länger unerreichbar.",
            "Die Reise geht weiter.",
            "Neue Abenteuer warten in der Unendlichkeit.",
            "Die Aurora bleibt ein Symbol der Hoffnung.",
            "Die Kristalle leuchten den Weg.",
            "Die Zukunft liegt in den Sternen.",
            "Die Mission der Aurora ist noch nicht zu Ende."
        ];